version: "3.7"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=test-api
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
  node-app:
    image: node-app
    depends_on:
      - mongodb
